package tools

//WeatherURL sets icon
func WeatherIcon(condition string) string {
	switch condition {
	case "113":
		return "http://fallenfocus.net/weatherpng/wi-day-sunny.png"
	case "116":
		return "http://fallenfocus.net/weatherpng/wi-day-cloudy-high.png"
	case "119":
		return "http://fallenfocus.net/weatherpng/wi-day-cloudy.png"
	case "122":
		return "http://fallenfocus.net/weatherpng/wi-day-cloudy.png"
	case "143":
		return "http://fallenfocus.net/weatherpng/wi-fog.png"
	case "176":
		return "http://fallenfocus.net/weatherpng/wi-day-showers.png"
	case "179":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "182":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "185":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "200":
		return "http://fallenfocus.net/weatherpng/wi-day-thunderstorm.png"
	case "227":
		return "http://fallenfocus.net/weatherpng/wi-day-snow.png"
	case "230":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "248":
		return "http://fallenfocus.net/weatherpng/wi-fog.png"
	case "260":
		return "http://fallenfocus.net/weatherpng/wi-fog.png"
	case "263":
		return "http://fallenfocus.net/weatherpng/wi-day-showers.png"
	case "266":
		return "http://fallenfocus.net/weatherpng/wi-day-rain.png"
	case "281":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "284":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "293":
		return "http://fallenfocus.net/weatherpng/wi-day-rain.png"
	case "296":
		return "http://fallenfocus.net/weatherpng/wi-day-rain.png"
	case "299":
		return "http://fallenfocus.net/weatherpng/wi-showers.png"
	case "302":
		return "http://fallenfocus.net/weatherpng/wi-rain-wind.png"
	case "305":
		return "http://fallenfocus.net/weatherpng/wi-showers.png"
	case "308":
		return "http://fallenfocus.net/weatherpng/wi-rain-wind.png"
	case "311":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "314":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "317":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "320":
		return "http://fallenfocus.net/weatherpng/wi-day-snow.png"
	case "323":
		return "http://fallenfocus.net/weatherpng/wi-day-rain-mix.png"
	case "326":
		return "http://fallenfocus.net/weatherpng/wi-day-rain-mix.png"
	case "329":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "332":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "335":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "338":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "350":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "353":
		return "http://fallenfocus.net/weatherpng/wi-day-showers.png"
	case "356":
		return "http://fallenfocus.net/weatherpng/wi-showers.png"
	case "359":
		return "http://fallenfocus.net/weatherpng/wi-rain-wind.png"
	case "362":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "365":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "368":
		return "http://fallenfocus.net/weatherpng/wi-day-rain-mix.png"
	case "371":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	case "374":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "377":
		return "http://fallenfocus.net/weatherpng/wi-sleet.png"
	case "386":
		return "http://fallenfocus.net/weatherpng/wi-day-thunderstorm.png"
	case "389":
		return "http://fallenfocus.net/weatherpng/wi-day-thunderstorm.png"
	case "392":
		return "http://fallenfocus.net/weatherpng/wi-day-snow-thunderstorm.png"
	case "395":
		return "http://fallenfocus.net/weatherpng/wi-snow-wind.png"
	default:
		return "http://fallenfocus.net/weatherpng/wi-na.png"
	}
}
